kafka:
  server: localhost:9092
  group:
    id: group1
spring:
  kafka:
    consumer:
      properties:
        isolation.level: read_committed
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      type: batch
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true